name: Extract Branch Prefix and Add Label

permissions:
  pull-requests: write
  issues: write

on:
  pull_request:
    branches:
      - develop

jobs:
  extract-branch-prefix:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Prefix from Branch Name
        id: extract_prefix
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          PREFIX=$(echo "$BRANCH_NAME" | cut -d'/' -f1)
          echo "::set-output name=prefix::$PREFIX"

      - name: Add Label to Pull Request
        uses: actions/github-script@v5
        with:
          script: |
            const prefix = "${{ steps.extract_prefix.outputs.prefix }}"
            const prNumber = context.issue.number;
            
            github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: [prefix],
              });

